### ISSUE TITLE
WireMock-as-Code adoption?

### ISSUE THREAD

**Issue by oleg-nenashev** [quarkiverse/quarkus-wiremock#41]
Hello, in WireMock we are looking for introducing better configuration capabilities, including serving all settings and CLI arguments via a YAML/JSON file, and also providing more YAML support in stub management. I guess such a feature would be really helpful for Quarkus users. Would anyone be interested?

**Comment by chberger** [comment]
Thank you for asking. Yes, such a feature would be really nice. Especially for the Quarkus integration it would be really helpful!
