### ISSUE TITLE
WireMock Extension for build-time configuration

### ISSUE THREAD

**Issue by oleg-nenashev** [quarkiverse/quarkus-wiremock#73]
Hi @chberger . I am thinking about building a Quarkus extension that allows to configure WireMock at the build time. I want to use it for a Quarkus flavor of https://github.com/wiremock/wiremock-docker , and for the native executable I want to implement in the future.

I guess it should be rather done in another repository, right?

**Comment by chberger** [comment]
Yeah, sounds like a different approach like this one.
